version: '3.8'

services:
  mysql:
    container_name: notes_mysql
    image: mysql:9.2.0
    environment:
      MYSQL_DATABASE: notes
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 127.0.0.1:3306:3306